name: 'niv Updater Action'
description: 'A GitHub action that detects updates to dependencies tracked by niv and creates pull requests to keep them up to date.'
author: 'knl'
runs:
  using: 'node12'
  main: 'main.js'
inputs:
  pull_request_base:
    description: 'The name of the branch to issue the pull requests against. Defaults to an empty string, which means to take the default branch for the repository.'
    required: false
    default: 'master'
  skip_versioned_revisions:
    description: 'If non-empty, will cause the action to skip updating any dependency that has a version in their revision. This is due to the way niv currently works, where it will always update to the latest HEAD of a branch. Thus, if one have a dependency where, for example, `rev=v1.0.0`, niv would normally update it to the latest head of the branch, making `rev` holding the appropriate SHA. This is something one would not normally expect. Thus, this option exists until niv fixes the behaviour.'
    required: false
    default: true
  skip_ssh_repos:
    description: 'If non-empty, will cause the action to skip updating any dependency that is hosted by a repo accessible via ssh.'
    required: false
    default: false
  whitelist:
    description: 'A list of dependencies, comma separated, that will be checked for updates. Other dependencies tracked by niv will not be checked for updates. This list will be consulted before the blacklist. It defaults to the list of all dependencies tracked by niv.'
    required: false
    default: ''
  blacklist:
    description: 'A list of dependencies, comma separated, to skip from updating. This list will be consulted after evaluating the whitelist.'
    required: false
    default: ''
  labels:
    description: 'A list of labels, *newline* separated, that will be applied to the generated PR. Defaults to an empty list.'
    required: false
    default: ''
branding:
  # maybe 'refresh-cw'
  icon: 'git-pull-request'
  color: 'orange'
